# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='short_url',
            field=models.URLField(default=None, verbose_name='URL Encurtada'),
            preserve_default=False,
        ),
    ]
