# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 01:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0005_auto_20160727_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='URL Encurtada'),
        ),
    ]
